apiVersion: v1
kind: Service
metadata:
  name: agronotaapp-service
  labels:
    run: agronotaapp
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30002
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: agronotaapp
  sessionAffinity: ClientIP